name: "aux flow"
description: "aux"

inputs:
  input:
    description: "Define apk path input"
    required: true

  version:
    description: "test version"
    required: true

  output:
    description: "Define apk path output"
    required: true

runs:
  using: "composite"

  steps:
    - name: print stuff
      env:
        input: ${{ inputs.input }}
        version: ${{ inputs.version }}
        output: ${{ inputs.output }}
        ghr: ${{ github.repository }}
      shell: bash
      run: |
        echo "running in branch test 2"
        echo "input: $input"
        echo "version: $version"
        echo "output: $output"
        echo "git hub repository: $ghr"
      
    